#!/bin/sh

#Get branch name
branch=$(git branch | grep "^\*" | sed "s/^\*\s//")

#Parse jira issue if any
jira_issue=$(echo "${branch}" | sed "s/.*[^A-Z]\([A-Z]\+-[0-9]\+\)[^0-9].*/\1/")

#Set jira_issue as suggested commit message
sed -i "1s/^/${jira_issue}/" ${1}
