#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t dio_build-XXXX.log)"
[ $VERBOSE ] && echo "Dionysusuipack dir is set to $DIO_DIR"
echo "Dionysusuipack build log: $LOG"
cd "$DIO_DIR"
grunt sass &> $LOG
