#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t hwa_build-XXXX.log)"
[ $VERBOSE ] && echo "HermewWebApp dir is set to $HWA_DIR"
echo "HermesWebApp build log: $LOG"
cd "$HWA_DIR"
mvn clean install -U -DskipTests=true &> $LOG
