#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t stub_build-XXXX.log)"
[ $VERBOSE ] && echo "Stub dir is set to $STUB_DIR"
echo "Stub build log: $LOG"
cd "$STUB_DIR"
mvn clean install -U -DskipTests=true &> $LOG
