#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t cap_build-XXXX.log)"
[ $VERBOSE ] && echo "Commonassetspack  dir is set to $CAP_DIR"
echo "Commonassetspack build log: $LOG"
cd "$CAP_DIR"
mvn clean install -U -DskipTests=true &> $LOG
