#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t ba_build-XXXX.log)"
[ $VERBOSE ] && echo "BookingApp dir is set to $BA_DIR"
echo "Booking App build log: $LOG"
cd "$BA_DIR"
mvn clean install -U -DskipTests=true &> $LOG
