#!/bin/bash -i
. `dirname $0`/env.conf
[ $VERBOSE ] && echo "Commonassetspack dir is set to $CAP_DIR"
cd "$CAP_DIR/cap-web"
start //MAX cmd //T:07 //k "mvn -Djetty.port=9091 -Djetty.secure.port=9192 jetty:run"
