#!/bin/bash -i
. `dirname $0`/env.conf
LOG="$(mktemp -t apache_update-XXXX.log)"
branch="windows-apache-2.4.16-x64"
[ $VERBOSE ] && echo "Apache dir is set to $APACHE_DIR"
echo "Apache update log from $branch branch: $LOG"
cd "$APACHE_DIR"
git checkout $branch &> $LOG && git pull &> $LOG
