version: "3"
services:

  styxdev:
    image: registry.docker.hcom/hotels/styxpres:release
    ports:
      - "9000:9000"
    environment:
      - APP_CONFIG_ENVIRONMENT=dev
      - APP_CONFIG_FILE_LOCATION=/styxconf/env.yaml
      - APP_LOG_CONFIG_LOCATION=/styxconf/logback.xml
      - ORIGINS_FILE=/styxconf/origins.yaml
      - APP_CONFIG_LOCATION=/hcom/servers/styx/config
      - APP_jvmRouteName=
      - APP_LOC_CLIENT_CACHE_THREADPOOL_SIZE_FOR_BOOTSTRAP=50
      - MAX_TIME_TO_WAIT=60
      - JVM_HEAP_SIZE=-Xms1536m -Xmx1536m
      - JVM_METASPACE=-XX:MetaspaceSize=100m -XX:MaxMetaspaceSize=100m -XX:MinMetaspaceFreeRatio=0 -XX:MaxMetaspaceFreeRatio=100
      - JVM_DIRECT_MEMORY=-XX:MaxDirectMemorySize=512m
      - JVM_OTHER_MEM=-XX:CompressedClassSpaceSize=20m -XX:InitialCodeCacheSize=50m -XX:ReservedCodeCacheSize=50m
      - JVM_HEAP_DUMP=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/tmp
      - JVM_FLIGHT_RECORDER=-XX:+UnlockCommercialFeatures -XX:+FlightRecorder
      - JAVA_OPTS= -Dfile.encoding=UTF-8
      - VAULT_ADDR=https://vault.lab.hcom
      - INSTANCE_NAME=staging1-styxpres-01
      - APPLICATION_NAME=styxpres
      - SECRETS_PATH=secret/app/styxpres/staging
      - FETCH_CREDENTIALS=1
    volumes:
      - ./conf/:/styxconf
      - ./appcert/:/appcert

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/fe-app-rules:/etc/nginx/fe-app-rules:ro
      - ./certs/:/certs/

  checkito:
    image: registry.docker.hcom/hotels/checkito:latest
    ports:
      - "8089:8089"
      - "8189:8189"

  configsvc:
    image: registry.docker.hcom/hotels/cws:latest
    ports:
      - "8280:8080"
    environment:
      - RUN_EMBEDDED_ETCD=true
    container_name: cws
