version: "3"
volumes:
  mvt:

services:

  styxdev:
    image: registry.docker.hcom/hotels/styxpres:release
    ports:
      - "9000:9000"
    environment:
      - APP_CONFIG_ENVIRONMENT=dev
      - APP_CONFIG_FILE_LOCATION=/styxconf/env.yaml
      - APP_LOG_CONFIG_LOCATION=/styxconf/logback.xml
      - ORIGINS_FILE=/styxconf/origins.yaml
      - APP_CONFIG_LOCATION=/hcom/servers/styx/config
      - APP_jvmRouteName=
      - APP_LOC_CLIENT_CACHE_THREADPOOL_SIZE_FOR_BOOTSTRAP=50
      - MAX_TIME_TO_WAIT=60
      - JVM_HEAP_SIZE=-Xms1536m -Xmx1536m
      - JVM_HEAP_SIZE=-Xmx4048M -Xms2000M
      - JVM_METASPACE=-XX:MetaspaceSize=200m -XX:MaxMetaspaceSize=200m -XX:MinMetaspaceFreeRatio=0 -XX:MaxMetaspaceFreeRatio=100
      - JVM_DIRECT_MEMORY=-XX:MaxDirectMemorySize=1536m
      - JVM_OTHER_MEM=-XX:CompressedClassSpaceSize=20m -XX:InitialCodeCacheSize=50m -XX:ReservedCodeCacheSize=50m
      - JVM_HEAP_DUMP=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/tmp
      - JVM_FLIGHT_RECORDER=-XX:+UnlockCommercialFeatures -XX:+FlightRecorder
      - JAVA_OPTS= -Dfile.encoding=UTF-8
      - VAULT_ADDR=https://vault.lab.hcom
      - INSTANCE_NAME=staging1-styxpres-01
      - APPLICATION_NAME=styxpres
      - SECRETS_PATH=secret/app/styxpres/staging
      - FETCH_CREDENTIALS=1
    volumes:
      - ./conf/:/styxconf
      - ./appcert/:/appcert

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/fe-app-rules:/etc/nginx/fe-app-rules:ro
      - ./certs/:/certs/

  mvt:
    volumes:
      - mvt:/mvt
    image: registry.docker.hcom/hotels/mvt:latest

  bka:
    ports:
      - "30443:8443"
      - "1901:1901"
    volumes:
      - mvt:/mvt
    image: registry.docker.hcom/hotels/ba:${BA_VERSION}
    environment:
      - APP_javax.net.ssl.trustStore=/hcom/servers/tomcat/certs/pvclient-karmalab.jks
      - APP_javax.net.ssl.trustStorePassword=tiajya
      - APP_javax.net.ssl.keyStore=/hcom/servers/tomcat/certs/pvclient-karmalab.jks
      - APP_javax.net.ssl.keyStorePassword=tiajya
      - APP_DIONYSUS_TEMPLATES_DOWNLOAD_PATH=/hcom/servers/tomcat/temp
      - APP_METRICS_GRAPHITE_REPORTING_INTERVAL=-1
      - APP_METRICS_BOOTSTRAPPER_METRIC_REGISTRATION_ENABLED=false
      - APP_METRICS_BOOTSTRAPPER_HEALTH_CHECK_REGISTRATION_ENABLED=false
      - APP_COOKIELESS_DOMAIN_STATIC_ASSETS=a.staging1-cdn-hotels.com
      - APP_DB_RO_DRIVERCLASSNAME=com.inet.tds.TdsDriver
      - APP_DB_RW_DRIVERCLASSNAME=com.inet.tds.TdsDriver
      - APP_CONFIG_ENVIRONMENT=hcom-devrom
      - APP_MVT_BUSINESS_CONFIGURATION_LOCATION=file:///mvt/
      - APP_DIONYSUS_UIPACK_HOME=file:///dionysusuipack/
      - APP_EMAIL_TEMPLATES_BASEPATH=file://${CATALINA_BASE}/appconfig/templates/
      - APP_LIS_EAPID=0
      - APP_BOOKING_SEND_CONFIRMATION_SMS=false
      - APP_SMS_CONFIRMATION_ENABLED=false
      - APP_spring.profiles.active=default,fakeauthentication
      - APP_VAULT_ADDR=https://vault.lab.hcom
      - APP_VAULT_USER_ID=staging1-ba-01
      - APP_VAULT_TIMEOUT=60
      - APP_TOMCAT_EXECUTOR_MAX_THREADS=50
      - APP_TOMCAT_EXECUTOR_MIN_SPARE_THREADS=10
      - APP_TOMCAT_EXECUTOR_MAX_IDLE_TIME=20000
      - APP_TOMCAT_EXECUTOR_MAX_QUEUE_SIZE=30
      - APP_DB_RO_URL="jdbc:inetdae7://HCOM_RO_staging.karmalab.net?database=HCOM_EMEA_PROD"
      - APP_DB_RO_USERNAME=emea_appRO
      - APP_DB_RO_PASSWORD=emea_appRO
      - APP_DB_RW_URL="jdbc:inetdae7://HCOM_EMEA_PROD_staging.karmalab.net?database=HCOM_EMEA_PROD"
      - APP_DB_RW_USERNAME=emea_app
      - APP_DB_RW_PASSWORD=emea_app
      - APP_DSC_DATASTAX_SSL_ENABLED=false
      - APP_DSC_DATASTAX_KEYSPACE_NAME=hermes
      #- APP_port.ajp=38099
      - JAVA_JVM_ARGS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1901

      # Proxy resources
      #- APP_http.proxyHost=checkito
      #- APP_http.proxyPort=8089
      #- APP_https.proxyHost=checkito
      #- APP_https.proxyPort=8089

      # Checkito resources
      - APP_DIONYSUS_TEMPLATE_PATH=http://dispatcherapp.staging1.hcom/templates/dionysus_ui_pack_templates-63.0.zip
      - APP_DOSSIER_SERVICES_HOST=checkito
      - APP_DOSSIER_SERVICES_PORT=8089
      - APP_DOSSIER_BASE_URL=http://checkito:8089/dossier
      - APP_EMAIL_SERVER_HOSTNAME=checkito
      - APP_EMAIL_SERVER_PORT=25
      - APP_LIS_DASUPPORT_BOOKING_XML_API_HOST=checkito
      - APP_LIS_DASUPPORT_BOOKING_XML_API_PLAIN_URL=http://checkito:8089/
      - APP_LIS_DASUPPORT_BOOKING_XML_API_PORT=8089
      - APP_LIS_DASUPPORT_XML_API_HOST=checkito
      - APP_LIS_DASUPPORT_XML_API_PLAIN_URL=http://checkito:8089/
      - APP_LIS_DASUPPORT_XML_API_PORT=8089
      - APP_PAYMENT_VAULT_SERVICE_HOST=checkito:8189
      - APP_PAYMENT_VAULT_SERVICE_ACCESS_PROTOCOL=https
      - APP_PROPERTY_CATALOGUE_SERVICE_BASE_URL=http://checkito:8089/property_catalogue_svc
      - APP_LOYALTY_SERVICE_HOST=checkito:8089
      - APP_STORED_VALUE_GATEWAY_ACCESS_PROTOCOL=https
      - APP_STORED_VALUE_GATEWAY_HOST=checkito:8089
      - APP_ORDER_SERVICE_URL=http://checkito:8089/OrderService?wsdl
      - APP_customer.data.store.svc=http://checkito:8089/customer_data_store_svc/v1_0
      - APP_CRYPTO_SERVICE_URL=http://checkito:8089/cryptosvc/cryptosvc.asmx
      - APP_CUSTOMER_AUTH_APP_BASE_URL=http://checkito:8089
      - APP_SPS_HOST=$LOCALHOST_NAME:8089
      - APP_VPS_HOST=$LOCALHOST_NAME:8089
      - APP_CAR_TRAWLER_BASE_URL=checkito:8089
      - APP_CAR_TRAWLER_SECURE_URL_ENABLED=false
      - APP_BPAS_HOST=checkito:8089
      - APP_COUPON_SERVICE_HOST=checkito
      - APP_COUPON_SERVICE_PORT=8089
      - APP_BRAVOS_API_DOMAIN_NAME=checkito
      - APP_BRAVOS_API_PORT=8089

      # Staging resources
      #- APP_DIONYSUS_TEMPLATE_PATH=http://10.187.108.40:34401/templates/dionysus_ui_pack_templates-63.0.zip
      #- APP_port.ajp=38099
      #- APP_DOSSIER_SERVICES_HOST=dossiersvcdocker.staging.hcom
      #- APP_DOSSIER_SERVICES_PORT=443
      #- APP_DOSSIER_BASE_URL=https://dossiersvcdocker.staging.hcom:443/dossier
      #- APP_EMAIL_SERVER_HOSTNAME=checkito
      #- APP_EMAIL_SERVER_PORT=25
      #- APP_LIS_DASUPPORT_BOOKING_XML_API_HOST=lodgingbookingservicepoint.integration.bgb.karmalab.net
      #- APP_LIS_DASUPPORT_BOOKING_XML_API_PLAIN_URL=http://lodgingbookingservicepoint.integration.bgb.karmalab.net:8080/
      #- APP_LIS_DASUPPORT_BOOKING_XML_API_PORT=8080
      #- APP_LIS_DASUPPORT_XML_API_HOST=lodgingshoppingservicepoint.integration.bgb.karmalab.net
      #- APP_LIS_DASUPPORT_XML_API_PLAIN_URL=http://lodgingshoppingservicepoint.integration.bgb.karmalab.net:8080/
      #- APP_LIS_DASUPPORT_XML_API_PORT=8080
      #- APP_PAYMENT_VAULT_SERVICE_HOST=paymentvault.karmalab.net
      #- APP_PAYMENT_VAULT_SERVICE_PORT=443
      #- APP_PAYMENT_VAULT_SERVICE_ACCESS_PROTOCOL=https
      #- APP_PAYMENT_VAULT_SERVICE_URL=https://paymentvault.karmalab.net/PaymentVault/v2?wsdl
      #- APP_PROPERTY_CATALOGUE_SERVICE_BASE_URL=http://hcom-pcs-stg.staging-hotels.com/property_catalogue_svc
      #- APP_STORED_VALUE_GATEWAY_ACCESS_PROTOCOL=http
      #- APP_CONFIRMATION_EMAIL_ADBANNER_OVER_HTTPS=false
      #- APP_IOVATION_ENABLED=true
      #- APP_TARGETING_BASE_URL=http://targettingservice.staging.hcom/targeting
      #- APP_CAR_TRAWLER_BASE_URL=checkito:8090
      #- APP_CAR_TRAWLER_SECURE_URL_ENABLED=false
      #- APP_CRYPTO_SERVICE_URL=http://cryptosvc.karmalab.net:80/cryptosvc/cryptosvc.asmx
      #- APP_LIS_XML_API_PLAIN_URL=http://lodgingshoppingservicepoint.integration.bgb.karmalab.net:8080
      #- APP_LSS_HOTEL_CONTENT_SERVICE_URL=http://chellssint01:52420/lcs
      #- APP_LSS_HOTEL_SHELL_SERVICE_URL=http://chellssint01:52410/lds
      #- APP_MHCR_LIVE_HOTEL_CONTENT_SERVICE_HOST=vipcheilssmhr001.karmalab.net
      #- APP_MHCR_LIVE_HOTEL_SHELL_SERVICE_HOST=vipcheilssmhr001.karmalab.net
      #- APP_ORDER_SERVICE_URL=http://omsservice.int-maui.karmalab.net:80/OrderService?wsdl
      #- APP_PASSBOOK_CERTIFICATES_PASSWORD=hotdEv12
      #- APP_PAYMENT_OPTION_SERVICE_URL=http://paymentoption.karmalab.net:80/PaymentOptions/v2?wsdl
      #- APP_PAYMENT_PROCESSOR_SERVICE_URL=https://paymentprocessor.karmalab.net:443/PaymentProcessor/v2?wsdl
      #- APP_MVTSERVICE_BASE_URL=http://mvtservice.staging.hcom/mvtsvc
      #- APP_BPAS_HOST=bookingpaymentavailabilityservice.staging.hcom
      #- JVM_HEAP_SIZE=-Xmx2048M -Xms512M

  checkito:
    image: registry.docker.hcom/hotels/checkito:latest
    ports:
      - "8089:8089"
      - "8189:8189"

  configsvc:
    image: registry.docker.hcom/hotels/cws:latest
    ports:
      - "8280:8080"
    environment:
      - RUN_EMBEDDED_ETCD=true
    container_name: cws
