#!/usr/bin/awk -f
BEGIN {
  FS=": "
  OFS=" "
  COLOR_RET="\033[7;49;37m"
  COLOR_ENT="\033[7;49;36m"
  COLOR_RESET="\033[0m"
  indentLevel=0
  INDENT_STRING=" -- "
}
function indent(level) {
  indentation = ""
  for (i=0; i<level; i++) {
        indentation = indentation INDENT_STRING
  }
  return indentation
}
{
  if ( $1 == "Returning" ) {
    indentLevel--
    print indent(indentLevel),COLOR_RET,$1,$2,COLOR_RESET;
  }
  if ($1 == "Entering") {
    print indent(indentLevel),COLOR_ENT,$1,$2,COLOR_RESET;
    indentLevel++
  } 
}
